# Generated by Django 4.2.8 on 2026-02-14 20:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list, help_text='List of required skills')),
                ('suitable_for', models.TextField(help_text='Description of suitable candidates')),
                ('average_salary_range', models.CharField(blank=True, help_text="e.g., '$80k - $150k'", max_length=100)),
                ('job_growth', models.CharField(blank=True, help_text="e.g., '12% annual growth'", max_length=50)),
                ('typical_companies', models.JSONField(default=list, help_text='List of typical employers')),
                ('required_education', models.CharField(blank=True, help_text="e.g., 'Bachelor in Computer Science'", max_length=255)),
                ('related_careers', models.JSONField(default=list, help_text='List of related career names')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('program_name', models.CharField(help_text="e.g., 'Bachelor of Computer Science'", max_length=255)),
                ('url', models.URLField(blank=True)),
                ('ranking', models.IntegerField(blank=True, help_text='University ranking in this field', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='careers.career')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ['career', 'ranking'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(help_text="e.g., 'Coursera', 'Udemy', 'University Name'", max_length=255)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('duration', models.CharField(blank=True, help_text="e.g., '3 months', '1 year'", max_length=100)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='careers.career')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['career', 'name'],
            },
        ),
    ]
