# Generated by Django 6.0.2 on 2026-02-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='ability_vector',
            field=models.JSONField(default=list, help_text='Pre-computed ability scores (15 dims)'),
        ),
        migrations.AddField(
            model_name='career',
            name='cluster',
            field=models.CharField(blank=True, help_text='High-level category used for diversity', max_length=100),
        ),
        migrations.AddField(
            model_name='career',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Cached embedding for semantic search (list)', null=True),
        ),
    ]
