# Generated by Django 4.2.8 on 2026-02-14 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('logic', 'Logical Thinking'), ('creativity', 'Creativity'), ('communication', 'Communication'), ('academic', 'Academic Performance'), ('interests', 'Interests'), ('work_style', 'Work Style')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed explanation of what this question assesses')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Quiz Question',
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Quiz Submission',
                'verbose_name_plural': 'Quiz Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_response', models.IntegerField(help_text='Rating or response value (typically 1-10 scale)')),
                ('session_id', models.CharField(db_index=True, help_text='Session or user identifier', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.quizquestion')),
            ],
            options={
                'verbose_name': 'Quiz Answer',
                'verbose_name_plural': 'Quiz Answers',
                'ordering': ['submitted_at'],
                'unique_together': {('session_id', 'question')},
            },
        ),
    ]
